# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ticker_service_pb2 as ticker__service__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ticker_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TickerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTickers = channel.unary_unary(
                '/ticker_service.TickerService/GetTickers',
                request_serializer=ticker__service__pb2.TickerRequest.SerializeToString,
                response_deserializer=ticker__service__pb2.TickerResponse.FromString,
                _registered_method=True)
        self.ConnectToMarketData = channel.unary_stream(
                '/ticker_service.TickerService/ConnectToMarketData',
                request_serializer=ticker__service__pb2.TickerRequest.SerializeToString,
                response_deserializer=ticker__service__pb2.MarketData.FromString,
                _registered_method=True)
        self.SubmitLimitOrder = channel.unary_unary(
                '/ticker_service.TickerService/SubmitLimitOrder',
                request_serializer=ticker__service__pb2.LimitOrderRequest.SerializeToString,
                response_deserializer=ticker__service__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.SubmitMarketOrder = channel.unary_unary(
                '/ticker_service.TickerService/SubmitMarketOrder',
                request_serializer=ticker__service__pb2.MarketOrderRequest.SerializeToString,
                response_deserializer=ticker__service__pb2.OrderResponse.FromString,
                _registered_method=True)


class TickerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTickers(self, request, context):
        """Get a list of available tickers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectToMarketData(self, request, context):
        """Connect to a stream of market data for a specific ticker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitLimitOrder(self, request, context):
        """Submit a limit order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitMarketOrder(self, request, context):
        """Submit a market order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TickerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTickers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTickers,
                    request_deserializer=ticker__service__pb2.TickerRequest.FromString,
                    response_serializer=ticker__service__pb2.TickerResponse.SerializeToString,
            ),
            'ConnectToMarketData': grpc.unary_stream_rpc_method_handler(
                    servicer.ConnectToMarketData,
                    request_deserializer=ticker__service__pb2.TickerRequest.FromString,
                    response_serializer=ticker__service__pb2.MarketData.SerializeToString,
            ),
            'SubmitLimitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitLimitOrder,
                    request_deserializer=ticker__service__pb2.LimitOrderRequest.FromString,
                    response_serializer=ticker__service__pb2.OrderResponse.SerializeToString,
            ),
            'SubmitMarketOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitMarketOrder,
                    request_deserializer=ticker__service__pb2.MarketOrderRequest.FromString,
                    response_serializer=ticker__service__pb2.OrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticker_service.TickerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ticker_service.TickerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TickerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTickers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticker_service.TickerService/GetTickers',
            ticker__service__pb2.TickerRequest.SerializeToString,
            ticker__service__pb2.TickerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectToMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ticker_service.TickerService/ConnectToMarketData',
            ticker__service__pb2.TickerRequest.SerializeToString,
            ticker__service__pb2.MarketData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitLimitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticker_service.TickerService/SubmitLimitOrder',
            ticker__service__pb2.LimitOrderRequest.SerializeToString,
            ticker__service__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitMarketOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticker_service.TickerService/SubmitMarketOrder',
            ticker__service__pb2.MarketOrderRequest.SerializeToString,
            ticker__service__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
