# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticker_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ticker_service.proto\x12\x0eticker_service\"&\n\rTickerRequest\x12\x15\n\rticker_symbol\x18\x01 \x01(\t\"=\n\x0eTickerResponse\x12+\n\x07tickers\x18\x01 \x03(\x0b\x32\x1a.ticker_service.TickerInfo\"*\n\nTickerInfo\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xea\x01\n\nMarketData\x12\x15\n\rticker_symbol\x18\x01 \x01(\t\x12\x16\n\x0e\x62\x65st_bid_price\x18\x02 \x01(\x01\x12\x16\n\x0e\x62\x65st_ask_price\x18\x03 \x01(\x01\x12\x19\n\x11\x62\x65st_bid_quantity\x18\x04 \x01(\x03\x12\x19\n\x11\x62\x65st_ask_quantity\x18\x05 \x01(\x03\x12\x1f\n\x17order_book_variance_max\x18\x06 \x01(\x01\x12\x1f\n\x17order_book_variance_min\x18\x07 \x01(\x01\x12\x1d\n\x15total_volume_quantity\x18\x08 \x01(\x03\"Y\n\x11LimitOrderRequest\x12\x15\n\rticker_symbol\x18\x01 \x01(\t\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\x03\"K\n\x12MarketOrderRequest\x12\x15\n\rticker_symbol\x18\x01 \x01(\t\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x03\"!\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t2\xde\x02\n\rTickerService\x12K\n\nGetTickers\x12\x1d.ticker_service.TickerRequest\x1a\x1e.ticker_service.TickerResponse\x12R\n\x13\x43onnectToMarketData\x12\x1d.ticker_service.TickerRequest\x1a\x1a.ticker_service.MarketData0\x01\x12T\n\x10SubmitLimitOrder\x12!.ticker_service.LimitOrderRequest\x1a\x1d.ticker_service.OrderResponse\x12V\n\x11SubmitMarketOrder\x12\".ticker_service.MarketOrderRequest\x1a\x1d.ticker_service.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticker_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TICKERREQUEST']._serialized_start=40
  _globals['_TICKERREQUEST']._serialized_end=78
  _globals['_TICKERRESPONSE']._serialized_start=80
  _globals['_TICKERRESPONSE']._serialized_end=141
  _globals['_TICKERINFO']._serialized_start=143
  _globals['_TICKERINFO']._serialized_end=185
  _globals['_MARKETDATA']._serialized_start=188
  _globals['_MARKETDATA']._serialized_end=422
  _globals['_LIMITORDERREQUEST']._serialized_start=424
  _globals['_LIMITORDERREQUEST']._serialized_end=513
  _globals['_MARKETORDERREQUEST']._serialized_start=515
  _globals['_MARKETORDERREQUEST']._serialized_end=590
  _globals['_ORDERRESPONSE']._serialized_start=592
  _globals['_ORDERRESPONSE']._serialized_end=625
  _globals['_TICKERSERVICE']._serialized_start=628
  _globals['_TICKERSERVICE']._serialized_end=978
# @@protoc_insertion_point(module_scope)
